[[language]]
name = "rust"
auto-format = true

[language.config.cargo]
features = [ "debug" ]

[language.config.check]
command = "clippy"

[[language]]
name = "nix"

[language.config]
nil.nix.flake.autoEvalInputs = true